name: dotnet build

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - "beta"
      - "prerelease"
      - "master"


jobs:
  build:
    env:
      name: ${{github.branch}}-${{github.sha}}
      ref: ${{github.ref_name}}-last
      retention: 5
      test: ${{ github.workspace }}/tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Upload sha build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact-${{env.name}}
        path: ${{ github.workspace }}/**/*
        retention-days: ${{env.retention}}
        
    - name: Upload build artifact to ${{env.ref}}
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact-${{env.ref}}
        path: ${{ github.workspace }}/**/*

    - name: Test
      run: dotnet test  --no-build --configuration Release --logger trx --results-directory ${{env.test}}
      continue-on-error: true
      
    - name: Process trx reports with default
      id: process-trx
      uses: im-open/process-dotnet-test-results@v2.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        ignore-test-failures: true
        base-directory: ${{env.test}}
    
    - name: Upload dotnet test results to ${{env.name}}
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{env.name}}-${{steps.process-trx.outputs.test-outcome}}
        path: ${{env.test}}/**/*
        retention-days: ${{env.retention}}
 
    - name: Upload dotnet test results to test-results-${{env.ref}}
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{env.ref}}-${{steps.process-trx.outputs.test-outcome}}
        path: ${{env.test}}/**/*
      if: steps.process-trx.outputs.test-outcome == 'Passed'

    - name: Fail if there were test problems
      if: steps.process-trx.outputs.test-outcome == 'Failed'
      run: |
        echo "There were test failures."
        exit 1


