name: dotnet build

on:
  workflow_call:
    inputs:
      build_artifact:
        description: 'The name of the build artifact'
        required: true
        type: string
        default: build-${{github.branch}}-${{github.sha}}
      test_artifact:
        description: 'The name of the test artifact'
        required: true
        type: string
        default: test-${{github.branch}}-${{github.sha}}
      retention:
        description: 'The number of days to retain the artifact'
        required: true
        default: 5
        type: number
  workflow_dispatch:
  push:
    branches:
      - "beta"
      - "prerelease"
      - "master"

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    env:      
      ref: ${{github.ref_name}}-last
      test: ${{ github.workspace }}/tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Upload sha build artifact to ${{inputs.build_artifact}}
      uses: actions/upload-artifact@v3
      with:
        name: ${{inputs.build_artifact}}
        path: ${{ github.workspace }}/**/*
        retention-days: ${{inputs.retention}}
        
    - name: Upload build artifact to ${{env.ref}}
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact-${{env.ref}}
        path: ${{ github.workspace }}/**/*

    - name: Test
      run: dotnet test  --no-build --configuration Release --logger trx --results-directory ${{env.test}}
      continue-on-error: true
      
    - name: Process trx reports with default
      id: process-trx
      uses: im-open/process-dotnet-test-results@v2.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        ignore-test-failures: true
        base-directory: ${{env.test}}
    
    - name: Upload dotnet test results to ${{inputs.test_artifact}}
      uses: actions/upload-artifact@v3
      with:
        name: ${{inputs.test_artifact}}
        path: ${{env.test}}/**/*
        retention-days: ${{inputs.retention}}
 
    - name: Upload dotnet test results to test-results-${{env.ref}}
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{env.ref}}-${{steps.process-trx.outputs.test-outcome}}
        path: ${{env.test}}/**/*
      if: steps.process-trx.outputs.test-outcome == 'Passed'

    - name: Fail if there were test problems
      if: steps.process-trx.outputs.test-outcome == 'Failed'
      run: |
        echo "There were test failures."
        exit 1


