name: dotnet build

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Target framework
        target:
          - net6.0
          - net7.0
        
  
  push:
    branches: [ main, master, beta, release, prerelease]
  pull_request:
    branches: [ main, master, beta, release, prerelease ]
  
jobs:
  build:
    with:
      name: ${{github.ref}}-${{github.sha}}
      ref: ${{github.ref}}-last
      retention: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Upload sha build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact-${{name}}
        path: ${{ github.workspace }}/**/*
        retention-days: 5
        
    - name: Upload build artifact to ${{ref}}
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact-${{ref}}
        path: ${{ github.workspace }}/**/*

    - name: Test
      run: dotnet test  --no-build --logger trx --results-directory "test-results"

    - name: Process trx reports with default
      if: always()
      # You may also reference just the major or major.minor version
      uses: im-open/process-dotnet-test-results@v2.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload dotnet test results to ${{name}}
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{name}}
        path: test-results/**/*
        retention-days: retention
      if: ${{ always() }}

    - name: Upload dotnet test results to ${{ref}}
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ref}}
        path: test-results/**/*
      if: ${{ always() }}


#    - name: Generate list using Markdown
#      run: |
#        echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
#        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
#        echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
#        echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
#        echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
#      if: ${{ always() }}

