name: Delete Releases

on:
  workflow_dispatch:
    inputs:
      threshold:
          description: 'The number of days to retain the artifact'
          required: false
          type: number
          default: 5
      draft:
          description: 'The number of days to retain the artifact'
          required: false
          type: boolean
          default: true
      branch:
          description: 'The branch to match'
          required: false
          type: string
      
      
  

jobs:
  list_draft_releases:
    runs-on: ubuntu-latest
    env:
      draft_pattern: "${{github.inputs.draft ? '-i -w draft' : ''}}"
      branch_pattern: "-i ${{github.inputs.branch}}"
    outputs:
      releases: ${{ steps.list_releases.outputs.releases }}
    steps:
      - echo "pattern: ${{env.pattern}}"
      - name: List draft releases
        id: list_releases
        run: |
         echo "releases=$(gh release list | grep  ${{env.draft_pattern}} | grep ${{env.branch_pattern}})" >> $GITHUB_OUTPUT
         echo $releases >> $GITHUB_STEP_SUMMARY
        
  build:
    runs-on: ubuntu-latest
    environment: clenup

    steps:
      - name: Delete drafts
        echo:  echo "$releases" |sed 's/|/ /' | awk '{print $1, $3}'  | while read -r release date; do echo $release; done
        
