name: dotnet test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main, master, release, prerelease]
  pull_request:
    branches: [ main, master, beta, release, prerelease ]
  
jobs:
 
  build:
 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6', '7']
    name: Test w/t ${{ matrix.dotnet }} 

    steps:

    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - uses: actions/cache@v3
      id: cache
      with:
        path: | 
         ~/build
         ~/reports
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}


    - name: Restore dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: dotnet restore
      
    - name: Build
      if: steps.cache.outputs.cache-hit != 'true'
      run: dotnet build --no-restore -o build
      
    - name: Test
      if: steps.cache.outputs.cache-hit != 'true'
      run: dotnet test build  --no-build --logger trx --results-directory "reports/${{ matrix.dotnet }}/tests"

    - name: Upload dotnet test results
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.dotnet }}
        path: reports/${{ matrix.dotnet }}/tests

    - uses: dorny/test-reporter@v1
      with:
        name: Test Report - net${{ matrix.dotnet }} 
        reporter: dotnet-trx
        path: "reports/**/*.trx"
      if: ${{ always() }}
#    - name: Summery Report
#      run: |
#        echo "- Test w/t ${{ matrix.dotnet }} done" >> $GITHUB_STEP_SUMMARY

