name: dotnet test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main, master, release, prerelease]
  pull_request:
    branches: [ main, master, beta, release, prerelease ]
  
jobs:
  cache: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: get
        with:
          path: path/to/dependencies
          key: ${{ runner.os }}-${{ hashFiles('Http.*/**') }}
    outputs: 
      include: steps.get.outputs
  
  restore-cache:
    if: jobs.cache.outputs.cache-hit == 'true'
    runs-on: ubuntu-latest
    steps:
       - name: Summery Report
         run: |
          echo "- Test results restored from cahce key = ${{ runner.os }}-${{ hashFiles('Http.*/**') }}" >> $GITHUB_STEP_SUMMARY

  build:
    needs: [ cache ]

    if: jobs.cache.outputs.cache-hit != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6', '7']
    name: Test w/t ${{ matrix.dotnet }} 

    steps:

    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test  --no-build --logger trx --results-directory "reports/${{ matrix.dotnet }}/tests"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.dotnet }}
        path: reports/${{ matrix.dotnet }}/tests
      if: ${{ always() }}
    - uses: dorny/test-reporter@v1
      with:
        name: Test Report - net${{ matrix.dotnet }} 
        reporter: dotnet-trx
        path: "reports/**/*.trx"
      if: ${{ always() }}
#    - name: Summery Report
#      run: |
#        echo "- Test w/t ${{ matrix.dotnet }} done" >> $GITHUB_STEP_SUMMARY

