name: dotnet test

on:
  workflow_dispatch:
  push:
    branches: [ main, master, beta, release, prerelease]
  pull_request:
    branches: [ main, master, beta, release, prerelease ]
  
jobs:
  build:
    

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6.*', '7.*']
    name: Test w/t ${{ matrix.dotnet }} 
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test  --no-build --logger trx --results-directory "test-results-${{ matrix.dotnet-version }}"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.dotnet-version }}
        path: test-results-${{ matrix.dotnet-version }}
      if: ${{ always() }}
    - uses: dorny/test-reporter@v1
      with:
        path: test-results-${{ matrix.dotnet-version }}
        name: test-results-${{ matrix.dotnet-version }}
        reporter: dotnet-trx
        fail-on-error: 'true'
        artifact: test-results-${{ matrix.dotnet-version }}
      if: ${{ always() }}
#    - name: Summery Report
#      run: |
#        echo "- Test w/t ${{ matrix.dotnet }} done" >> $GITHUB_STEP_SUMMARY

